before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq wget
 - mkdir -p /home/travis/.cpan/sources/modules
 - (cd /home/travis/.cpan/sources/modules && wget http://cpan.cpantesters.org/modules/02packages.details.txt.gz)
# only needed for plack.t
 - cpanm --quiet --notest Image::Info Plack::Test CGI::Emulate::PSGI CGI::Compile
# optional, by default Storable is used
 - cpanm --quiet --notest Sereal::Encoder Sereal::Decoder
before_script:
 - (cd cgi-bin && ln -s cpantestersmatrix.yml.travis cpantestersmatrix.yml)
# fix shebang for plackup operation
 - (cd cgi-bin && env PERL=$(which perl) perl -pe '$_ = "#!$ENV{PERL} -T\n" if $. == 1' cpantestersmatrix.pl > cpantestersmatrix-travis.pl && chmod 755 cpantestersmatrix-travis.pl)
language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.14"
  - "5.10"
